name: Gitee repos mirror periodic job
on:
# 如果需要PR触发把push前的#去掉
# push:
  schedule:
    # 每天北京时间9点跑
    - cron:  '0 1 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/gitee-mirror-action@v0.01
      with:
        # Gitee对应的秘钥
        private_key: ${{ secrets.gitee }}
        # 需要同步的Github组织名（源）
        github_org: kscript
        # 需要同步到的Gitee的组织名（目的）
        gitee_org: kscript
