name: Gitee repos mirror periodic job

on: [ push, delete, create ]

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.gitee }}
        with:
          source-repo: 'git@github.com:kscript/challenge.git'
          destination-repo: 'git@bitbucket.org:kscript/challenge.git'
