name: Sync to Gitee
on: 
  push:
    branchs:
      - master
jobs:
  sync:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.gitee }}
        with:
          source-repo: 'git@github.com:kscript/challenge.git'
          destination-repo: 'git@gitee.com:kscript/challenge.git'